### ISSUE TITLE
Error: Internal error in `dict_hash_with()`: Dictionary is full

### ISSUE THREAD

**Issue by LZarri** [therkildsen-lab/data-processing#7]
The summarize_depth_per_position.R script generates the first three files:

..._depth_per_position_per_sample_summary.tsv
..._depth_per_position_all_samples.txt
..._presence_per_position_all_samples.txt

But then crashes with the generation of the histograms. It seems from reading the forums that perhaps the tibble should be converted to dataframe? https://stackoverflow.com/questions/64563951/dictionary-is-full-error-message-using-dplyr

Input script
nohup Rscript \
/workdir/data-processing/scripts/summarize_depth_per_position.R \
"/workdir/smallmouth/sample_lists/bam_list_realigned_smb_anchored.txt" \
"/workdir/smallmouth/sample_lists/sample_table_merged_smb_anchored.tsv" \
"/workdir/smallmouth/" \
> /workdir/smallmouth/nohups/summarize_depth_per_position.out 2>&1 &

Files generated
-rw-r----- 1 ljz27 nt246_0001 2.9G Sep 29 01:38 bam_list_realigned_smb_anchored_presence_per_position_all_samples.txt
-rw-r----- 1 ljz27 nt246_0001 3.0G Sep 28 23:53 bam_list_realigned_smb_anchored_depth_per_position_all_samples.txt
-rw-r----- 1 ljz27 nt246_0001  16K Sep 28 21:49 bam_list_realigned_smb_anchored_depth_per_position_per_sample_summary.tsv

**Comment by nicolas931010** [comment]
This is caused by a issue in the `vctrs` package (see tidyverse/tidyr/issues/713). It has been fixed in the development version of the package, and you can download the development version by running 
``` r
devtools::install_github("r-lib/vctrs")
```

**Comment by cnemeczek** [comment]
Hello, I was getting the same dict_hash_with():Dictionary if full error while using the summarize_depth_per_position.R script and installed the developers version of vctrs, but am still getting the same error.

**Comment by LZarri** [comment]
Have you tried uninstalling vctrs and then re-installing just the developers version? I'm wondering if it is still calling the non-developers version

**Comment by nicolas931010** [comment]
Thanks, @LZarri! 

@cnemeczek, if you still can't get this to work, I've actually skipped this `samtools depth` step in my own workflow. Instead, I now use ANGSD to do a depth count at all sites before SNP calling to set up the depth filters. This way, I can use some of the ANGSD filters, and it takes much less time. 

Here are some [instructions](https://github.com/therkildsen-lab/genomic-data-analysis/blob/master/markdowns/angsd_global_snp_calling.md#depth-filters). Please ignore the `-GL 1 -doMajorMinor 1 -doMaf 1` part; I don' t think those are needed.

**Comment by cnemeczek** [comment]
Thanks @LZarri I used remove.packages() to remove vctrs and then reinstalled the developers version, but it is still giving me the error. I am using a computer cluster, and perhaps there is a different way to do this? 

Thanks @nicolas931010 , I will try this out.
